ci: pin runner version to Ubuntu 20.04
Now the `ubuntu-latest` label points to Ubuntu 22.04 instead of 20.04.
Due to this fact, the tarantool/setup-tarantool action installed Jammy
tarantool package and the following error occurred in the case of 1.10:

    LuajitError: /usr/bin/tarantoolctl:923: module 'luarocks.core.cfg' not found:
        no field package.preload['luarocks.core.cfg']
        no file './luarocks/core/cfg.lua'
        no file './luarocks/core/cfg/init.lua'
        no file './luarocks/core/cfg.so'
        no file '/home/runner/work/luatest/luatest/.rocks/share/tarantool/luarocks/core/cfg.lua'
        no file '/home/runner/work/luatest/luatest/.rocks/share/tarantool/luarocks/core/cfg/init.lua'
        no file '/home/runner/work/luatest/.rocks/share/tarantool/luarocks/core/cfg.lua'
        no file '/home/runner/
    fatal error, exiting the event loop

Pin the runner version to Ubuntu 20.04 to avoid the error above.